import type { Scene } from "@babylonjs/core/scene";
import type { Mesh } from "@babylonjs/core/Meshes/mesh";
import type { LinesMesh } from "@babylonjs/core/Meshes/linesMesh";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import { VertexData } from "@babylonjs/core/Meshes/mesh.vertexData";
import { Mesh as MeshClass } from "@babylonjs/core/Meshes/mesh";
import { Material } from "@babylonjs/core/Materials/material";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { Color3, Vector3 } from "@babylonjs/core/Maths/math";

import type { NodeId, RoadGraph, Segment } from "../sim/graph";
import type { Vec3 } from "../sim/vec";
import type { TerrainBounds } from "../sim/heightmap";
import {
  baseRoadTypeId,
  laneCentres,
  ROAD_LIFT,
  roadType,
  SIDEWALK_LIFT,
  SIDEWALK_WIDTH,
  walkCentres,
  type RoadType,
} from "../sim/roadTypes";
import {
  allJunctions,
  ringElevation,
  ringLaneRadii,
  segmentTrims,
  widestIncidentRoad,
  type JunctionArm,
  type JunctionGeometry,
} from "../sim/junction";
import { normalizeXZ, perpXZ } from "../sim/vec";
import { laneRank, ringEntryRadius } from "../sim/routing";
import {
  CROSSING_DEPTH,
  CROSSING_GAP,
  armPort,
  crossesRoad,
  crossingNear,
  walkLoop,
  walkTransfers,
  junctionTurnPath,
  laneChangeOffset,
  laneChangeSpan,
  onRing,
  ringCrossPath,
  ringJoinPath,
  ringOf,
  ringWalkJoin,
  walkRingRadius,
} from "../sim/transfers";

/** A highway's guardrail, standing where a sidewalk would otherwise go. */
const GUARDRAIL_HEIGHT = 0.85;

/** Zebra stripes: painted on the carriageway just outside the junction each arm runs into. */
const STRIPE_WIDTH = 0.9;
const MARK_LIFT = ROAD_LIFT + 0.05;

/** Every possible lane-to-lane movement through an ordinary junction, in the Traffic view. */
const turnColor = new Color3(0.75, 0.5, 0.95);
/** Same idea, for every possible crossing a pedestrian could make between two arms' sidewalks. */
const walkTurnColor = new Color3(0.55, 0.85, 0.55);

/**
 * Turns the graph into road surface. Every mesh here is derived: `rebuild` disposes what
 * it made and builds again from the graph, and nothing else ever touches these meshes.
 * ponytail: module-size is kept here because roads, junctions, crossings, tunnels and portals all
 * share the same Babylon materials and transfer geometry; split when one render pass can own less.
 */
export function createRoadRenderer(scene: Scene, graph: RoadGraph, heightAt: (x: number, z: number) => number) {
  const material = new StandardMaterial("road", scene);
  material.diffuseColor = new Color3(0.18, 0.18, 0.19);
  const industrialMaterial = new StandardMaterial("industrial_road", scene);
  industrialMaterial.diffuseColor = new Color3(0.13, 0.14, 0.14);
  industrialMaterial.specularColor = Color3.Black();
  const dirtMaterial = new StandardMaterial("dirt_road", scene);
  dirtMaterial.diffuseColor = new Color3(0.36, 0.26, 0.16);
  dirtMaterial.specularColor = Color3.Black();
  const militaryMaterial = new StandardMaterial("military_road", scene);
  militaryMaterial.diffuseColor = new Color3(0.12, 0.18, 0.13);
  militaryMaterial.specularColor = Color3.Black();
  const industrialPaintMaterial = new StandardMaterial("industrial_paint", scene);
  industrialPaintMaterial.diffuseColor = new Color3(0.95, 0.62, 0.16);
  industrialPaintMaterial.specularColor = Color3.Black();
  // A footpath in the same asphalt as a street reads as a street. Paving reads as somewhere to walk.
  const pavingMaterial = new StandardMaterial("paving", scene);
  pavingMaterial.diffuseColor = new Color3(0.56, 0.53, 0.48);
  pavingMaterial.specularColor = Color3.Black();
  // Footway strips are generated by several builders -- straight runs, junction corners, arcs
  // around a ring -- and their winding depends on which way each one walks its points. They are
  // all flat and seen from above, so drawing both faces is cheaper than getting every winding
  // right. ponytail: one flag, not four orientation arguments.
  pavingMaterial.backFaceCulling = false;
  const paintMaterial = new StandardMaterial("road_paint", scene);
  paintMaterial.diffuseColor = new Color3(0.88, 0.88, 0.85);
  paintMaterial.specularColor = Color3.Black();
  material.specularColor = Color3.Black();
  const portalMaterial = new StandardMaterial("tunnel_portal", scene);
  portalMaterial.diffuseColor = new Color3(0.26, 0.25, 0.23);
  portalMaterial.specularColor = Color3.Black();
  const tubeMaterial = new StandardMaterial("tunnel_tube", scene);
  tubeMaterial.diffuseColor = new Color3(0.06, 0.06, 0.055);
  tubeMaterial.emissiveColor = new Color3(0.01, 0.008, 0.006);
  tubeMaterial.specularColor = Color3.Black();
  const curb = new Color3(0.52, 0.55, 0.53);
  const lane = new Color3(0.86, 0.78, 0.48);
  const tunnel = new Color3(0.58, 0.55, 0.49);
  // The Traffic view's own lane overlay: one colour per direction of travel, so how many lanes a
  // road has and which way each one flows both read at a glance.
  const laneOutbound = new Color3(0.3, 0.85, 0.95);
  const laneInbound = new Color3(0.95, 0.45, 0.25);
  // A distinct pair for foot traffic, so a sidewalk's lane doesn't read as one more car lane.
  const walkOutbound = new Color3(0.55, 0.9, 0.4);
  const walkInbound = new Color3(0.95, 0.85, 0.35);
  const guardrailMaterial = new StandardMaterial("guardrail", scene);
  guardrailMaterial.emissiveColor = new Color3(0.62, 0.64, 0.65);
  guardrailMaterial.specularColor = Color3.Black();
  guardrailMaterial.disableLighting = true;
  guardrailMaterial.backFaceCulling = false;

  let meshes: (Mesh | LinesMesh)[] = [];
  let trafficMeshes: LinesMesh[] = [];
  let faded = false;

  /**
   * The Traffic view's own use for this: the lane overlay is the thing to read, so the road
   * surface and everything painted on it fade back rather than competing with it -- except the
   * overlay's own lines, which are the one thing this view exists to make MORE visible, not less.
   * The solid meshes (asphalt, paving, paint, guardrail) share one material each, so setting it
   * once reaches every mesh built from it; a `LinesMesh` (kerbs, dividers) has no material to
   * share, so each one already in `meshes` gets its own alpha directly.
   */
  function applyFade(): void {
    const alpha = faded ? 0.35 : 1;
    for (const m of [material, industrialMaterial, dirtMaterial, militaryMaterial, industrialPaintMaterial, pavingMaterial, paintMaterial, guardrailMaterial]) {
      m.alpha = alpha;
      m.transparencyMode = alpha < 1 ? Material.MATERIAL_ALPHABLEND : Material.MATERIAL_OPAQUE;
    }
    for (const mesh of meshes) {
      if (mesh.name.startsWith("traffic_lane_") || mesh.name.startsWith("traffic_walk_")) continue;
      if ("alpha" in mesh) (mesh as LinesMesh).alpha = alpha;
    }
  }
  let showTraffic = false;

  function disposeTrafficOverlay(): void {
    for (const mesh of trafficMeshes) mesh.dispose();
    trafficMeshes = [];
  }

  function rebuildTrafficOverlay(junctions: Map<NodeId, JunctionGeometry> = allJunctions(graph)): void {
    disposeTrafficOverlay();
    if (!showTraffic) return;

    for (const seg of graph.allSegments()) {
      const type = roadType(seg.type);
      if (type.tunnelDepth) {
        const steps = Math.max(4, Math.ceil(seg.length / 8));
        for (const [i, laneCentre] of laneCentres(type).entries()) {
          const points = pointsBetween(graph, seg.id, 0, seg.length, steps, MARK_LIFT + 0.02, heightAt, laneCentre.offset);
          trafficMeshes.push(styledLine(scene, `traffic_lane_${seg.id}_${i}`, points, laneCentre.direction === 1 ? laneOutbound : laneInbound));
        }
        continue;
      }

      const { start, end } = segmentTrims(junctions, graph, seg.id);
      const from = start;
      const to = seg.length - end;
      if (to - from < 0.25) continue;
      const steps = Math.max(2, Math.ceil((to - from) / 2));

      if (!type.pedestrian) {
        for (const [i, laneCentre] of laneCentres(type).entries()) {
          const points = pointsBetween(graph, seg.id, from, to, steps, MARK_LIFT + 0.02, heightAt, laneCentre.offset);
          trafficMeshes.push(styledLine(scene, `traffic_lane_${seg.id}_${i}`, points, laneCentre.direction === 1 ? laneOutbound : laneInbound));
        }
        trafficMeshes.push(...laneChangeLines(scene, graph, seg, type, from, to, turnColor));
      }
      if (!type.highway) {
        const walkLift = type.pedestrian ? MARK_LIFT + 0.02 : SIDEWALK_LIFT + 0.03;
        for (const [i, walkCentre] of walkCentres(type, SIDEWALK_WIDTH).entries()) {
          const points = pointsBetween(graph, seg.id, from, to, steps, walkLift, heightAt, walkCentre.offset);
          trafficMeshes.push(styledLine(scene, `traffic_walk_${seg.id}_${i}`, points, walkCentre.direction === 1 ? walkOutbound : walkInbound));
        }
      }
    }

    for (const junction of junctions.values()) {
      if (junction.roundabout > 0) {
        const centre = graph.node(junction.node).pos;
        const elevationAt = ringElevation(junction.arms, centre.y);
        const radii = ringLaneRadii(graph, junction.node, junction.roundabout);
        for (const [i, radius] of radii.entries()) {
          const points = Array.from({ length: 65 }, (_, s) => {
            const angle = (s / 64) * Math.PI * 2;
            const y = elevationAt(angle) + MARK_LIFT + 0.02;
            return new Vector3(centre.x + Math.cos(angle) * radius, y, centre.z + Math.sin(angle) * radius);
          });
          trafficMeshes.push(styledLine(scene, `traffic_lane_roundabout_${junction.node}_${i}`, points, laneOutbound));
        }
        trafficMeshes.push(...roundaboutTurnLines(scene, graph, junction, radii, turnColor));
      } else {
        trafficMeshes.push(...junctionTurnLines(scene, graph, junction, turnColor));
      }
      for (const [i, path] of walkTransferPaths(graph, junction, junctions).entries()) {
        trafficMeshes.push(styledLine(scene, `traffic_walk_turn_${junction.node}_${i}`, lift(path, SIDEWALK_LIFT + 0.03), walkTurnColor));
      }
    }
  }

  function rebuild(dirty?: TerrainBounds, junctions: Map<NodeId, JunctionGeometry> = allJunctions(graph)): void {
    if (dirty) {
      const segmentsById = new Map(graph.allSegments().map((segment) => [segment.id, segment]));
      meshes = meshes.filter((mesh) => {
        if (!meshTouchesDirty(segmentsById, mesh, dirty)) return true;
        mesh.dispose();
        return false;
      });
    } else {
      for (const mesh of meshes) mesh.dispose();
      meshes = [];
    }

    for (const seg of graph.allSegments()) {
      const type = roadType(seg.type);
      if (dirty && !segmentMeshTouchesBounds(seg.samples, type, dirty)) continue;
      if (type.tunnelDepth) {
        const steps = Math.max(4, Math.ceil(seg.length / 8));
        const trace = pointsBetween(graph, seg.id, 0, seg.length, steps, MARK_LIFT, heightAt);
        const line = MeshBuilder.CreateDashedLines(`tunnel_trace_${seg.id}`, { points: trace, dashSize: 8, gapSize: 5 }, scene);
        line.color = tunnel;
        line.isPickable = false;

        const tube = tunnelMesh(scene, `tunnel_${seg.id}`, graph, seg.id, steps, type.width);
        tube.shell.material = portalMaterial;
        tube.interior.material = tubeMaterial;
        tube.shell.isPickable = false;
        tube.interior.isPickable = false;
        meshes.push(line, tube.shell, tube.interior);
        meshes.push(...tunnelPortals(scene, graph, seg.id, type.width, portalMaterial, tunnel, heightAt));
        continue;
      }

      const half = type.width / 2;
      const isAvenue = baseRoadTypeId(seg.type) === "avenue" || type.industrial;
      // The surface stops short of each junction; the junction polygon closes the gap.
      const { start, end } = segmentTrims(junctions, graph, seg.id);
      const from = start;
      const to = seg.length - end;
      if (to - from < 0.25) continue; // wholly inside its junctions

      const left: Vector3[] = [];
      const right: Vector3[] = [];
      const steps = Math.max(2, Math.ceil((to - from) / 2));
      for (let i = 0; i <= steps; i++) {
        const d = from + ((to - from) * i) / steps;
        const { position, tangent } = graph.pointAt(seg.id, d);
        const n = perpXZ(normalizeXZ(tangent));
        left.push(new Vector3(position.x + n.x * half, position.y + ROAD_LIFT, position.z + n.z * half));
        right.push(new Vector3(position.x - n.x * half, position.y + ROAD_LIFT, position.z - n.z * half));
      }

      const ribbon = roadStripMesh(scene, `road_${seg.id}`, left, right);
      const baseId = baseRoadTypeId(seg.type);
      ribbon.material = type.pedestrian ? pavingMaterial : baseId === "dirt" ? dirtMaterial : baseId === "military" ? militaryMaterial : type.industrial ? industrialMaterial : material;
      ribbon.isPickable = false;
      meshes.push(ribbon);
      meshes.push(styledLines(scene, `curb_${seg.id}`, [left, right], curb));
      if (type.industrial) {
        for (const side of type.oneWay ? [-1, 1] : [-1, 0, 1]) {
          const points = pointsBetween(graph, seg.id, from, to, steps, MARK_LIFT + 0.04, heightAt, side * half * 0.45);
          const mark = MeshBuilder.CreateTube(`industrial_mark_${seg.id}_${side}`, { path: points, radius: 0.18, tessellation: 4 }, scene);
          mark.material = industrialPaintMaterial;
          mark.isPickable = false;
          meshes.push(mark);
        }
      }

      // A footway either side, stepped up from the carriageway. A path is already all footway.
      // A highway gets no frontage to walk to, so it gets a guardrail in place of the sidewalk.
      if (type.highway) {
        const topLeft = left.map((p) => p.add(new Vector3(0, GUARDRAIL_HEIGHT, 0)));
        const topRight = right.map((p) => p.add(new Vector3(0, GUARDRAIL_HEIGHT, 0)));
        const railLeft = roadStripMesh(scene, `guardrail_l_${seg.id}`, left, topLeft);
        const railRight = roadStripMesh(scene, `guardrail_r_${seg.id}`, right, topRight);
        for (const rail of [railLeft, railRight]) {
          rail.material = guardrailMaterial;
          rail.isPickable = false;
          meshes.push(rail);
        }
        if (isElevatedBridge(seg, heightAt)) meshes.push(...cableBridge(scene, graph, seg, type.width, guardrailMaterial, curb));
      } else if (!type.pedestrian) {
        const outerLeft: Vector3[] = [];
        const outerRight: Vector3[] = [];
        const innerLeft: Vector3[] = [];
        const innerRight: Vector3[] = [];
        for (let i = 0; i <= steps; i++) {
          const d = from + ((to - from) * i) / steps;
          const { position, tangent } = graph.pointAt(seg.id, d);
          const n = perpXZ(normalizeXZ(tangent));
          const y = position.y + SIDEWALK_LIFT;
          const out = half + SIDEWALK_WIDTH;
          innerLeft.push(new Vector3(position.x + n.x * half, y, position.z + n.z * half));
          outerLeft.push(new Vector3(position.x + n.x * out, y, position.z + n.z * out));
          innerRight.push(new Vector3(position.x - n.x * half, y, position.z - n.z * half));
          outerRight.push(new Vector3(position.x - n.x * out, y, position.z - n.z * out));
        }
        alignSidewalkEnds(junctions, seg, outerLeft, outerRight);
        // Both footways of a road in one mesh: same paving, same lifetime, and one draw instead
        // of two on every road in the city.
        const walk = roadStripMesh(scene, `sidewalk_${seg.id}`, outerLeft, innerLeft, [innerRight, outerRight]);
        walk.material = pavingMaterial;
        walk.isPickable = false;
        meshes.push(walk);
      }
      // A two-way avenue always gets a centre line (it is wide enough to read as two directions);
      // a 2-lane two-way road gets the same line as its lane divider. One-way never draws one --
      // there is no opposing direction to keep apart, so no lane count on a one-way road needs it.
      if (!type.oneWay && (isAvenue || type.lanes === 2)) {
        const center = pointsBetween(graph, seg.id, from, to, steps, MARK_LIFT, heightAt);
        meshes.push(styledLine(scene, `lane_${seg.id}`, center, lane));
      }

    }

    // A crossing wherever someone on foot has to walk over a carriageway to get where the
    // footways go -- read off those transfers themselves, so the paint marks a real movement
    // rather than every arm on principle. A highway carries no footway, so nothing crosses it.
    for (const junction of junctions.values()) {
      if (dirty && !junctionTouchesBounds(junction, dirty)) continue;
      const paths = walkCrossings(graph, junction, junctions);
      for (const arm of junction.arms) {
        const type = roadType(graph.segment(arm.segment).type);
        if (type.tunnelDepth || type.pedestrian) continue;
        const reach = arm.trim + CROSSING_GAP + CROSSING_DEPTH * 2;
        if (!crossesRoad(graph.node(junction.node).pos, arm.outward, reach, paths)) continue;
        // How much road there is between this junction and whatever is at the other end.
        const room = roomOn(graph, junctions, arm, junction.node);
        meshes.push(...crossingMeshes(scene, graph, junction.node, arm, type.width, paintMaterial, room));
      }
    }

    for (const junction of junctions.values()) {
      if (dirty && !junctionTouchesBounds(junction, dirty)) continue;
      if (junction.roundabout > 0) {
        meshes.push(...roundaboutMeshes(scene, graph, junction, material, curb, pavingMaterial, lane));
        continue;
      }
      const mesh = junctionMesh(scene, junction);
      if (!mesh) continue;
      mesh.material = material;
      mesh.isPickable = false;
      meshes.push(mesh);
      // The footways have to close around the junction too, or every sidewalk stops dead at it.
      meshes.push(...junctionFootway(scene, graph, junction, pavingMaterial));
    }

    rebuildTrafficOverlay(junctions);
    applyFade();
  }

  return {
    rebuild,
    material,
    setShowTraffic(next: boolean) {
      if (showTraffic === next) return;
      showTraffic = next;
      rebuildTrafficOverlay();
    },
    setFaded(next: boolean) {
      // See buildings.ts's setFaded: reassigning transparencyMode to the value it already has,
      // on every tool-bar click, was enough to corrupt unrelated thin-instanced meshes' draw state.
      if (next === faded) return;
      faded = next;
      applyFade();
    },
    dispose(): void {
      for (const mesh of meshes) mesh.dispose();
      meshes = [];
      disposeTrafficOverlay();
      for (const m of [material, industrialMaterial, dirtMaterial, militaryMaterial, industrialPaintMaterial, pavingMaterial, paintMaterial, portalMaterial, tubeMaterial, guardrailMaterial]) m.dispose();
    },
  };
}

/**
 * One zebra across an arm, laid just beyond where the junction surface ends. Stripes run along
 * the road, so they read as a crossing rather than as lane markings.
 * ponytail: a strip mesh per stripe, reusing the ribbon builder the roads already use.
 */
function crossingMeshes(
  scene: Scene,
  graph: RoadGraph,
  nodeId: NodeId,
  arm: JunctionArm,
  width: number,
  paint: StandardMaterial,
  room: number,
): Mesh[] {
  const seg = graph.segment(arm.segment);
  const atStart = seg.a === nodeId;
  // Sits just clear of the junction, and gives up that clearance before it gives up the crossing
  // itself: a roundabout holds its arms back by a whole ring radius, so a road between two of
  // them has far less room than its length suggests -- and people cross it all the same.
  const near = crossingNear(arm, room);
  const far = near + CROSSING_DEPTH;
  if (room < CROSSING_DEPTH) return [];

  const half = width / 2;
  const stripes = Math.max(2, Math.floor(width / (STRIPE_WIDTH * 2)));
  const pitch = width / stripes;
  const out: Mesh[] = [];

  // Both rows run the way the segment does, and the two sides keep the road ribbon's own order
  // of left and right. Laid from the junction outwards instead, a crossing at the near end of a
  // road came out wound the other way up and was culled away: whether one showed at all came
  // down to which direction that road happened to have been drawn in.
  const rows = [near, far].map((d) => (atStart ? d : seg.length - d)).sort((l, r) => l - r);

  // Every stripe of one crossing in a single mesh. They are four vertices each and never move
  // apart, so a mesh per stripe bought nothing and cost a draw call each -- on a real city that
  // was the largest single group of meshes in the scene, by a factor of three.
  const positions: number[] = [];
  const indices: number[] = [];
  for (let i = 0; i < stripes; i++) {
    const centre = -half + pitch * (i + 0.5);
    const base = positions.length / 3;
    for (const along of rows) {
      const { position, tangent } = graph.pointAt(arm.segment, along);
      const n = perpXZ(normalizeXZ(tangent));
      const lo = centre - STRIPE_WIDTH / 2;
      const hi = centre + STRIPE_WIDTH / 2;
      const y = position.y + MARK_LIFT;
      positions.push(position.x + n.x * hi, y, position.z + n.z * hi);
      positions.push(position.x + n.x * lo, y, position.z + n.z * lo);
    }
    indices.push(base, base + 1, base + 2, base + 1, base + 3, base + 2);
  }
  if (!positions.length) return out;
  const crossing = new MeshClass(`crossing_${arm.segment}_${nodeId}`, scene);
  const data = new VertexData();
  data.positions = positions;
  data.indices = indices;
  data.normals = Array.from({ length: positions.length / 3 }, () => [0, 1, 0]).flat();
  data.applyToMesh(crossing);
  crossing.material = paint;
  crossing.isPickable = false;
  out.push(crossing);
  return out;
}

function roundaboutMeshes(
  scene: Scene,
  graph: RoadGraph,
  junction: JunctionGeometry,
  surface: StandardMaterial,
  kerb: Color3,
  paving: StandardMaterial,
  laneColor: Color3,
): Mesh[] {
  const centre = graph.node(junction.node).pos;
  const outer = junction.roundabout;
  const reference = widestIncidentRoad(graph, junction.node);
  const lane = Math.max(6, reference?.width ?? 0);
  const inner = Math.max(3, outer - lane);
  // A ring between footpaths is paved, like the paths themselves.
  const onFoot = reference?.pedestrian === true;

  // A flat ring at one elevation only agrees with every road meeting it if the ground is flat
  // too -- on a slope, an arm arrives at its own elevation, not the node's, and a flat ring can
  // come out above or below it, showing as a gap right at the seam. Reading the ring's height
  // off the same per-arm elevations the arms' own corners already carry, blended smoothly
  // between one arm and the next, means the ring always meets every road exactly where it is.
  const elevationAt = ringElevation(junction.arms, centre.y);

  const ringPoints = (radius: number) => roundaboutArc(centre, radius, 0, Math.PI * 2, elevationAt, ROAD_LIFT);
  const ring = roadStripMesh(scene, `roundabout_${junction.node}`, ringPoints(inner), ringPoints(outer));
  ring.material = onFoot ? paving : surface;
  ring.isPickable = false;

  const circle = (radius: number): Vector3[] =>
    Array.from({ length: 41 }, (_, i) => {
      const angle = (i / 40) * Math.PI * 2;
      return new Vector3(centre.x + Math.cos(angle) * radius, elevationAt(angle) + MARK_LIFT, centre.z + Math.sin(angle) * radius);
    });

  const lanes = graph.node(junction.node).roundaboutLanes;

  return [
    ring,
    ...roundaboutArmPatches(scene, graph, junction, surface, paving, elevationAt),
    // A footway ring outside it, but broken where the arms come in: a full lathe would lay a band
    // straight across every road meeting the roundabout. A path is all footway already.
    ...(onFoot ? [] : footwayArcs(scene, graph, junction, centre, outer, elevationAt, paving)),
    styledLine(scene, `roundabout_kerb_in_${junction.node}`, circle(inner), kerb),
    // A second lane's own divider, the same colour as a straight road's centre line.
    ...(lanes === 2 && !onFoot ? [styledLine(scene, `roundabout_lane_${junction.node}`, circle((inner + outer) / 2), laneColor)] : []),
  ];
}

/** Interpolate the rendered 40-sided ring, including each crossed vertex: analytic circles leave slivers. */
function roundaboutArc(centre: Vec3, radius: number, from: number, to: number, elevationAt: (angle: number) => number, lift: number): Vector3[] {
  const step = Math.PI * 2 / 40;
  const angles = [from];
  for (let i = Math.floor(from / step) + 1; i * step < to - 1e-8; i++) angles.push(i * step);
  angles.push(to);
  const point = (angle: number) => new Vector3(centre.x + Math.cos(angle) * radius, elevationAt(angle) + lift, centre.z + Math.sin(angle) * radius);
  return angles.map((angle) => {
    const lo = Math.floor(angle / step) * step;
    return Vector3.Lerp(point(lo), point(lo + step), (angle - lo) / step);
  });
}

function roundaboutMouth(graph: RoadGraph, junction: JunctionGeometry, arm: JunctionArm) {
  const segment = graph.segment(arm.segment);
  const atStart = segment.a === junction.node;
  const { position, tangent } = graph.pointAt(segment.id, atStart ? arm.trim : segment.length - arm.trim);
  const outward = new Vector3(tangent.x, 0, tangent.z).scale(atStart ? 1 : -1).normalize();
  const normal = new Vector3(-outward.z, 0, outward.x);
  const centre = graph.node(junction.node).pos;
  const angle = Math.atan2(position.z - centre.z, position.x - centre.x);
  const type = roadType(segment.type);
  const half = type.width / 2;
  const spread = Math.asin(Math.min(0.95, (half + (type.highway || type.pedestrian ? 0 : SIDEWALK_WIDTH)) / junction.roundabout));
  return { position, outward, normal, angle, spread, half, type };
}

/** Quadratic corner tangent to the approach and to the ring; Y blends between the two actual surfaces. */
function roundaboutCorner(start: Vector3, end: Vector3, inward: Vector3, centre: Vec3): Vector3[] {
  const step = Math.PI * 2 / 40;
  const angle = (Math.floor(Math.atan2(end.z - centre.z, end.x - centre.x) / step) + 0.5) * step;
  const tangent = new Vector3(-Math.sin(angle), 0, Math.cos(angle));
  const cross = inward.x * tangent.z - inward.z * tangent.x;
  const delta = end.subtract(start);
  const distance = Math.abs(cross) > 1e-6 ? (delta.x * tangent.z - delta.z * tangent.x) / cross : 0;
  const control = start.add(inward.scale(Math.max(0, Math.min(distance, delta.length()))));
  return Array.from({ length: 9 }, (_, i) => {
    const t = i / 8, u = 1 - t;
    const p = start.scale(u * u).add(control.scale(2 * u * t)).add(end.scale(t * t));
    p.y = start.y + (end.y - start.y) * t;
    return p;
  });
}

function roundaboutArmPatches(
  scene: Scene,
  graph: RoadGraph,
  junction: JunctionGeometry,
  surface: StandardMaterial,
  paving: StandardMaterial,
  elevationAt: (angle: number) => number,
): Mesh[] {
  const centre = graph.node(junction.node).pos;
  return junction.arms.flatMap((arm) => {
    const { position, outward, normal, angle, spread, half, type } = roundaboutMouth(graph, junction, arm);
    const arc = roundaboutArc(centre, junction.roundabout, angle - spread, angle + spread, elevationAt, ROAD_LIFT);
    const mouth = (side: number, width: number, lift: number) => new Vector3(position.x + normal.x * side * width, position.y + lift, position.z + normal.z * side * width);
    const low = roundaboutCorner(mouth(-1, half, ROAD_LIFT), arc[0]!, outward.scale(-1), centre);
    const high = roundaboutCorner(mouth(1, half, ROAD_LIFT), arc.at(-1)!, outward.scale(-1), centre);
    // Blend the arc into the mouth without changing either end tangent and folding the grid.
    const rows = low.map((_, row) => arc.map((p, i) => {
      let a = Math.atan2(p.z - centre.z, p.x - centre.x) - angle;
      a = Math.atan2(Math.sin(a), Math.cos(a));
      const u = i === 0 ? 0 : i === arc.length - 1 ? 1 : Math.max(0, Math.min(1, (a + spread) / (2 * spread)));
      const t = row / 8;
      return Vector3.Lerp(low[row]!, high[row]!, u).add(p.subtract(Vector3.Lerp(arc[0]!, arc.at(-1)!, u)).scale(t * t * (3 - 2 * t)));
    }));
    const strips = rows.slice(1).map((row, i): [Vector3[], Vector3[]] => [row, rows[i]!]);
    const [first, ...rest] = strips;
    const asphalt = roadStripMesh(scene, `roundabout_gap_${arm.segment}_${junction.node}`, first![0], first![1], ...rest);
    asphalt.material = type.pedestrian ? paving : surface;
    asphalt.isPickable = false;
    const meshes = [asphalt];
    if (!type.highway && !type.pedestrian) {
      for (const [side, edge] of [[-1, low], [1, high]] as const) {
        const joinAngle = angle + side * spread;
        const end = roundaboutArc(centre, junction.roundabout + SIDEWALK_WIDTH, joinAngle, joinAngle, elevationAt, SIDEWALK_LIFT)[0]!;
        const outside = roundaboutCorner(mouth(side, half + SIDEWALK_WIDTH, SIDEWALK_LIFT), end, outward.scale(-1), centre);
        const inside = edge.map((p) => p.add(new Vector3(0, SIDEWALK_LIFT - ROAD_LIFT, 0)));
        const walk = roadStripMesh(scene, `roundabout_corner_${arm.segment}_${junction.node}_${side}`, inside, outside);
        walk.material = paving;
        walk.isPickable = false;
        meshes.push(walk);
      }
    }
    // The short connector has no room for an island before the zebra crossing; omit the old spike.
    return meshes;
  });
}

function alignSidewalkEnds(junctions: Map<NodeId, JunctionGeometry>, seg: Segment, outerLeft: Vector3[], outerRight: Vector3[]): void {
  const start = junctions.get(seg.a);
  const startArm = start?.arms.find((arm) => arm.segment === seg.id);
  if (start && start.roundabout === 0 && startArm) {
    outerLeft[0] = sidewalkOuterCorner(start, startArm.cornerHigh) ?? outerLeft[0]!;
    outerRight[0] = sidewalkOuterCorner(start, startArm.cornerLow) ?? outerRight[0]!;
  }

  const end = junctions.get(seg.b);
  const endArm = end?.arms.find((arm) => arm.segment === seg.id);
  if (end && end.roundabout === 0 && endArm) {
    outerLeft[outerLeft.length - 1] = sidewalkOuterCorner(end, endArm.cornerLow) ?? outerLeft[outerLeft.length - 1]!;
    outerRight[outerRight.length - 1] = sidewalkOuterCorner(end, endArm.cornerHigh) ?? outerRight[outerRight.length - 1]!;
  }
}

export function sidewalkOuterCorner(junction: JunctionGeometry, corner: Vec3): Vector3 | null {
  const ring = junction.ring;
  const i = ring.findIndex((point) => sameXZ(point, corner));
  if (i < 0) return null;
  const centroid = junctionCentroid(junction);
  const edges: [Vec3, Vec3][] = [
    [ring[(i - 1 + ring.length) % ring.length]!, ring[i]!],
    [ring[i]!, ring[(i + 1) % ring.length]!],
  ];
  const edge = edges.find(([a, b]) => !junctionMouthEdge(junction, a, b));
  if (!edge) return null;
  const [a, b] = edge;
  const dx = b.x - a.x;
  const dz = b.z - a.z;
  const length = Math.hypot(dx, dz);
  if (length < 0.05) return null;
  let nx = -dz / length;
  let nz = dx / length;
  if (nx * ((a.x + b.x) / 2 - centroid.x) + nz * ((a.z + b.z) / 2 - centroid.z) < 0) {
    nx = -nx;
    nz = -nz;
  }
  return new Vector3(corner.x + nx * SIDEWALK_WIDTH, corner.y + SIDEWALK_LIFT, corner.z + nz * SIDEWALK_WIDTH);
}

function sameXZ(a: Vec3, b: Vec3): boolean {
  return Math.hypot(a.x - b.x, a.z - b.z) < 0.15;
}

function junctionMouthEdge(junction: JunctionGeometry, a: Vec3, b: Vec3): boolean {
  return junction.arms.some(
    (arm) =>
      (sameXZ(a, arm.cornerLow) && sameXZ(b, arm.cornerHigh)) || (sameXZ(a, arm.cornerHigh) && sameXZ(b, arm.cornerLow)),
  );
}

function junctionCentroid(junction: JunctionGeometry): { x: number; z: number } {
  return junction.ring.reduce((sum, p) => ({ x: sum.x + p.x / junction.ring.length, z: sum.z + p.z / junction.ring.length }), {
    x: 0,
    z: 0,
  });
}


/**
 * Closes the footway around an ordinary junction. The junction polygon already has exactly the
 * right outline: each edge is either the mouth of a road, or a stretch of kerb between two roads.
 * Sweeping every non-mouth edge outwards gives the corner paving, and cannot cut across the
 * junction the way joining arm corners pairwise could.
 * ponytail: walk the hull that is already computed, rather than deriving a second polygon.
 */
function junctionFootway(
  scene: Scene,
  graph: RoadGraph,
  junction: JunctionGeometry,
  paving: StandardMaterial,
): Mesh[] {
  const ring = junction.ring;
  if (ring.length < 3) return [];

  const centroid = junctionCentroid(junction);
  // Two neighbouring arms each compute their shared corner independently, from their own
  // (possibly curved) centreline -- they land within a few centimetres of each other, not
  // exactly on top. A tighter epsilon here misses that match, misreads the mouth as a kerb
  // gap, and pastes a sidewalk patch straight onto the carriageway.
  /** True when this edge is where a road opens onto the junction, which must stay clear. */
  const isMouth = (a: Vec3, b: Vec3): boolean => junctionMouthEdge(junction, a, b);

  // A narrower road can meet this node without ever reaching the hull -- its corners sit
  // inside the ring, pulled behind the wider roads either side of it. The kerb edge that
  // "closes" the gap those wide roads leave then actually runs straight over that narrower
  // road's own mouth. Detected by bearing rather than distance: does any arm open into the
  // angular span this edge sweeps?
  const nodePos = graph.node(junction.node).pos;
  const bearingOf = (p: Vec3): number => Math.atan2(p.z - nodePos.z, p.x - nodePos.x);
  const norm = (angle: number): number => {
    let d = angle % (Math.PI * 2);
    if (d > Math.PI) d -= Math.PI * 2;
    if (d < -Math.PI) d += Math.PI * 2;
    return d;
  };
  const hasHiddenArm = (a: Vec3, b: Vec3): boolean => {
    const span = norm(bearingOf(b) - bearingOf(a));
    return junction.arms.some((arm) => {
      const d = norm(arm.angle - bearingOf(a));
      return span >= 0 ? d > 1e-3 && d < span - 1e-3 : d < -1e-3 && d > span + 1e-3;
    });
  };

  // Every corner of one junction in a single mesh: same paving, same lifetime, and a junction
  // has as many corners as it has arms.
  const strips: [Vector3[], Vector3[]][] = [];
  for (let i = 0; i < ring.length; i++) {
    const a = ring[i]!;
    const b = ring[(i + 1) % ring.length]!;
    if (isMouth(a, b)) continue;
    // Left unpaved rather than paved wrong: routing the patch around the hidden arm's own
    // mouth needs the corner points of an arm that never made it into `ring` -- more geometry
    // than this closes for. ponytail: skip the corner instead of getting it wrong.
    if (hasHiddenArm(a, b)) continue;

    const dx = b.x - a.x;
    const dz = b.z - a.z;
    const length = Math.hypot(dx, dz);
    if (length < 0.05) continue;
    // Outward normal: perpendicular to the edge, pointing away from the middle of the junction.
    let nx = -dz / length;
    let nz = dx / length;
    if (nx * ((a.x + b.x) / 2 - centroid.x) + nz * ((a.z + b.z) / 2 - centroid.z) < 0) {
      nx = -nx;
      nz = -nz;
    }
    const inner = [
      new Vector3(a.x, a.y + SIDEWALK_LIFT, a.z),
      new Vector3(b.x, b.y + SIDEWALK_LIFT, b.z),
    ];
    const outer = [
      new Vector3(a.x + nx * SIDEWALK_WIDTH, a.y + SIDEWALK_LIFT, a.z + nz * SIDEWALK_WIDTH),
      new Vector3(b.x + nx * SIDEWALK_WIDTH, b.y + SIDEWALK_LIFT, b.z + nz * SIDEWALK_WIDTH),
    ];
    strips.push([outer, inner]);
  }
  if (strips.length === 0) return [];
  const [first, ...rest] = strips;
  const patch = roadStripMesh(scene, `sidewalk_corner_${junction.node}`, first![0], first![1], ...rest);
  patch.material = paving;
  patch.isPickable = false;
  return [patch];
}

/**
 * The Traffic view's turn diagram for an ordinary junction: every incoming lane on every arm,
 * curved through to every outgoing lane on every OTHER arm -- the game does not model which
 * turns a lane (or a pedestrian crossing) is actually allowed to make, so this draws every
 * movement that is geometrically possible, the same way a real turning-movement diagram would
 * before restrictions are applied. Shared by cars (`laneCentres`) and foot traffic
 * (`walkCentres`): a road's sidewalks connect to the next one's exactly the same way its
 * carriageway does, just with a different set of lanes and a different exclusion.
 *
 * Which lanes are "incoming" or "outgoing" depends on which end of its own segment this arm sits
 * on: `lanesFor` labels lanes by which way distance increases along the segment, not by which
 * way they face this particular node, so that has to be flipped at the `b` end.
 */
/**
 * The merges and exits of a roundabout: one curve per lane of each arm, into the ring lane that
 * lane feeds and out of the outer one, plus the crossing between ring lanes that leaving from
 * the outer lane forces. Every curve here is the one the traffic actually drives -- both sides
 * build it from `sim/transfers`.
 */
function roundaboutTurnLines(
  scene: Scene,
  graph: RoadGraph,
  junction: JunctionGeometry,
  radii: readonly number[],
  color: Color3,
): LinesMesh[] {
  const ring = ringOf(graph, junction, radii);
  const outer = radii[radii.length - 1]!;
  const lines: LinesMesh[] = [];

  for (const arm of junction.arms) {
    const seg = graph.segment(arm.segment);
    const type = roadType(seg.type);
    if (type.pedestrian) continue;
    const atStart = seg.a === junction.node;
    const lanes = laneCentres(type);

    for (const [i, lane] of lanes.entries()) {
      const joining = atStart ? lane.direction === -1 : lane.direction === 1;
      // A lane joins the ring lane it feeds -- kerb-side onto the outer one, the lane beside the
      // centreline onto the inner. Leaving is only ever done from the outer lane.
      const radius = joining ? ringEntryRadius(radii, laneRank(lanes, lane)) : outer;
      const points = ringJoinPath(graph, ring, arm, lane.offset, radius, joining);
      lines.push(styledLine(scene, `traffic_ring_turn_${junction.node}_${arm.segment}_${i}`, lift(points, MARK_LIFT + 0.02), color));
    }

    if (radii.length > 1 && junction.arms.length > 1) {
      // Aimed at the kerb-side lane of this arm, which is the lane an exit is taken from.
      const kerb = lanes.find((lane) => laneRank(lanes, lane) === 0) ?? lanes[0]!;
      const spiral = ringCrossPath(graph, ring, arm, kerb.offset);
      lines.push(styledLine(scene, `traffic_ring_cross_${junction.node}_${arm.segment}`, lift(spiral, MARK_LIFT + 0.02), color));
    }
  }
  return lines;
}

/** Lifts a path off the surface it was computed on and into Babylon's own vectors. */
function lift(points: readonly Vec3[], by: number): Vector3[] {
  return points.map((p) => new Vector3(p.x, p.y + by, p.z));
}



/**
 * The weave between a road's own lanes: the line a car takes when it moves over, one per
 * direction that actually has two lanes to move between. Same stretch, same easing the traffic
 * uses, from `sim/transfers`.
 */
function laneChangeLines(
  scene: Scene,
  graph: RoadGraph,
  seg: { id: number; length: number },
  type: RoadType,
  from: number,
  to: number,
  color: Color3,
): LinesMesh[] {
  const lanes = laneCentres(type);
  const span = laneChangeSpan(from, to);
  const lines: LinesMesh[] = [];
  for (const direction of [1, -1] as const) {
    const sameWay = lanes.filter((lane) => lane.direction === direction);
    if (sameWay.length < 2) continue;
    const [a, b] = [sameWay[0]!.offset, sameWay[1]!.offset];
    const points = Array.from({ length: 13 }, (_, i) => {
      const t = i / 12;
      const d = direction === 1 ? span.start + (span.end - span.start) * t : span.end - (span.end - span.start) * t;
      const { position, tangent } = graph.pointAt(seg.id, d);
      const n = perpXZ(normalizeXZ(tangent));
      const offset = laneChangeOffset(a, b, t);
      return new Vector3(position.x + n.x * offset, position.y + MARK_LIFT + 0.03, position.z + n.z * offset);
    });
    lines.push(styledLine(scene, `traffic_lane_change_${seg.id}_${direction === 1 ? "out" : "in"}`, points, color));
  }
  return lines;
}


/**
 * The walks people actually make at this node, as opposed to the footway drawn round it: what a
 * crossing has to be answerable to. At a roundabout the footway circles it, so the ways round it
 * are the ways round it; at a junction the loop is closed and contains crossings nobody needs.
 */
function walkCrossings(graph: RoadGraph, junction: JunctionGeometry, junctions: Map<NodeId, JunctionGeometry>): Vec3[][] {
  if (junction.roundabout > 0) return walkTransferPaths(graph, junction, junctions);
  const loop = walkLoop(graph, junction, SIDEWALK_WIDTH, (arm) => roomOn(graph, junctions, arm, junction.node));
  return walkTransfers(graph, junction, loop);
}

/** How much of an arm is road rather than junction: its length less the trim at either end. */
function roomOn(graph: RoadGraph, junctions: Map<NodeId, JunctionGeometry>, arm: JunctionArm, nodeId: NodeId): number {
  const seg = graph.segment(arm.segment);
  const trims = segmentTrims(junctions, graph, arm.segment);
  return seg.length - arm.trim - (seg.a === nodeId ? trims.end : trims.start);
}

/**
 * Every way someone on foot gets across or around a node: the turn from each arm's arriving
 * walkway to every other arm's departing one, or, at a roundabout, the footway that circles it
 * and the step onto that footway from each arm. One list, three uses -- the Traffic view draws
 * it, the walkers walk it, and the zebra crossings are placed where it runs over a carriageway.
 */
function walkTransferPaths(graph: RoadGraph, junction: JunctionGeometry, junctions: Map<NodeId, JunctionGeometry>): Vec3[][] {
  const onFoot = (arm: JunctionArm) => roadType(graph.segment(arm.segment).type);
  const paths: Vec3[][] = [];

  if (junction.roundabout > 0) {
    const ring = ringOf(graph, junction, ringLaneRadii(graph, junction.node, junction.roundabout));
    const radius = walkRingRadius(ring, SIDEWALK_WIDTH);
    paths.push(Array.from({ length: 65 }, (_, i) => onRing(ring, (i / 64) * Math.PI * 2, radius)));
    for (const arm of junction.arms) {
      if (onFoot(arm).highway) continue; // a guardrail where the footway would be
      for (const walk of walkCentres(onFoot(arm), SIDEWALK_WIDTH)) {
        paths.push(ringWalkJoin(graph, ring, arm, walk.offset, radius));
      }
    }
    return paths;
  }

  const loop = walkLoop(graph, junction, SIDEWALK_WIDTH, (arm) => roomOn(graph, junctions, arm, junction.node));
  return loop.points.length > 0 ? [[...loop.points, loop.points[0]!]] : [];
}


function junctionTurnLines(scene: Scene, graph: RoadGraph, junction: JunctionGeometry, color: Color3): LinesMesh[] {
  interface Port {
    readonly position: Vec3;
    readonly armSegment: number;
  }
  const incoming: Port[] = [];
  const outgoing: Port[] = [];

  for (const arm of junction.arms) {
    const seg = graph.segment(arm.segment);
    const type = roadType(seg.type);
    if (type.pedestrian) continue; // its own foot transfers are drawn, not a turn diagram
    const atStart = seg.a === junction.node;
    for (const lane of laneCentres(type)) {
      const arrivingHere = atStart ? lane.direction === -1 : lane.direction === 1;
      (arrivingHere ? incoming : outgoing).push({
        position: armPort(graph, junction.node, arm, lane.offset),
        armSegment: arm.segment,
      });
    }
  }

  const centre = graph.node(junction.node).pos;
  const lines: LinesMesh[] = [];
  for (const [i, from] of incoming.entries()) {
    for (const [j, to] of outgoing.entries()) {
      if (from.armSegment === to.armSegment) continue; // no U-turn back onto the arm it came from
      const points = junctionTurnPath(centre, from.position, to.position);
      lines.push(styledLine(scene, `traffic_turn_${junction.node}_${i}_${j}`, lift(points, MARK_LIFT + 0.02), color));
    }
  }
  return lines;
}

/**
 * The gaps between the arms, each swept into a strip of footway. Each arm blocks the angle its
 * own carriageway and sidewalks subtend at the ring, so the footway meets them rather than
 * crossing them.
 */
function footwayArcs(
  scene: Scene,
  graph: RoadGraph,
  junction: JunctionGeometry,
  centre: Vec3,
  outer: number,
  elevationAt: (angle: number) => number,
  paving: StandardMaterial,
): Mesh[] {
  const blocked = junction.arms
    .map((arm) => {
      const { angle, spread } = roundaboutMouth(graph, junction, arm);
      return { angle, spread };
    })
    .sort((l, r) => l.angle - r.angle);
  if (blocked.length === 0) return [];

  const strips: [Vector3[], Vector3[]][] = [];
  for (const [i, arm] of blocked.entries()) {
    const next = blocked[(i + 1) % blocked.length]!;
    const from = arm.angle + arm.spread;
    const to = next.angle - next.spread + (i === blocked.length - 1 ? Math.PI * 2 : 0);
    if (to - from < 0.05) continue; // arms nearly touching: no room for a walkway between them

    const near = roundaboutArc(centre, outer, from, to, elevationAt, SIDEWALK_LIFT);
    const far = roundaboutArc(centre, outer + SIDEWALK_WIDTH, from, to, elevationAt, SIDEWALK_LIFT);
    strips.push([far, near]);
  }
  if (strips.length === 0) return [];
  const [first, ...rest] = strips;
  const walk = roadStripMesh(scene, `roundabout_walk_${junction.node}`, first![0], first![1], ...rest);
  walk.material = paving;
  walk.isPickable = false;
  return [walk];
}

/** Several lines that live and die together -- both kerbs of a road, say -- as one mesh. */
function styledLines(scene: Scene, name: string, lines: Vector3[][], color: Color3): LinesMesh {
  const mesh = MeshBuilder.CreateLineSystem(name, { lines }, scene);
  mesh.color = color;
  mesh.isPickable = false;
  return mesh;
}

function styledLine(scene: Scene, name: string, points: Vector3[], color: Color3, close = false): LinesMesh {
  const mesh = MeshBuilder.CreateLines(name, { points: close ? [...points, points[0]!] : points }, scene);
  mesh.color = color;
  mesh.isPickable = false;
  return mesh;
}

function isElevatedBridge(seg: Segment, heightAt: (x: number, z: number) => number): boolean {
  return seg.length > 1000 && seg.samples.some((p) => p.y - heightAt(p.x, p.z) > 8);
}

function cableBridge(
  scene: Scene,
  graph: RoadGraph,
  seg: Segment,
  width: number,
  material: StandardMaterial,
  color: Color3,
): (Mesh | LinesMesh)[] {
  const out: (Mesh | LinesMesh)[] = [];
  for (const d of [seg.length * 0.22, seg.length * 0.5, seg.length * 0.78]) {
    const { position, tangent } = graph.pointAt(seg.id, d);
    const n = perpXZ(normalizeXZ(tangent));
    for (const side of [-1, 1]) {
      const foot = new Vector3(position.x + n.x * side * width * 0.46, position.y, position.z + n.z * side * width * 0.46);
      const pierBase = -18;
      const pierHeight = foot.y - pierBase;
      const pier = MeshBuilder.CreateBox(`bridge_pier_${seg.id}_${d}_${side}`, { width: 7, height: pierHeight, depth: 7 }, scene);
      pier.position.set(foot.x, pierBase + pierHeight / 2, foot.z);
      pier.material = material;
      pier.isPickable = false;
      out.push(pier);
      const towerHeight = 126;
      const tower = MeshBuilder.CreateBox(`bridge_pylon_${seg.id}_${d}_${side}`, { width: 5, height: towerHeight, depth: 5 }, scene);
      tower.position.set(foot.x, foot.y + towerHeight / 2, foot.z);
      tower.material = material;
      tower.isPickable = false;
      out.push(tower);
      const top = new Vector3(foot.x, foot.y + towerHeight, foot.z);
      for (const span of [-180, -110, 110, 180]) {
        const deck = graph.pointAt(seg.id, Math.min(seg.length, Math.max(0, d + span))).position;
        const anchor = new Vector3(deck.x + n.x * side * width * 0.42, deck.y + GUARDRAIL_HEIGHT, deck.z + n.z * side * width * 0.42);
        out.push(styledLine(scene, `bridge_cable_${seg.id}_${d}_${side}_${span}`, [top, anchor], color));
      }
    }
  }
  return out;
}

function pointsTouchBounds(points: readonly Vec3[], bounds: TerrainBounds): boolean {
  return points.some((p) => p.x >= bounds.minX && p.x <= bounds.maxX && p.z >= bounds.minZ && p.z <= bounds.maxZ);
}

export function segmentMeshTouchesBounds(points: readonly Vec3[], type: Pick<RoadType, "width" | "highway" | "pedestrian">, bounds: TerrainBounds): boolean {
  const pad = type.highway || type.pedestrian ? type.width / 2 : type.width / 2 + SIDEWALK_WIDTH;
  const expanded = { minX: bounds.minX - pad, maxX: bounds.maxX + pad, minZ: bounds.minZ - pad, maxZ: bounds.maxZ + pad };
  for (let i = 0; i < points.length; i++) {
    const a = points[i]!;
    if (pointTouchesBounds(a, expanded)) return true;
    const b = points[i + 1];
    if (b && segmentTouchesBounds(a, b, expanded)) return true;
  }
  return false;
}

function junctionTouchesBounds(junction: JunctionGeometry, bounds: TerrainBounds): boolean {
  return pointsTouchBounds(junction.ring, bounds) || junction.arms.some((arm) => pointsTouchBounds([arm.cornerLow, arm.cornerHigh], bounds));
}

function meshTouchesDirty(segmentsById: Map<number, { samples: readonly Vec3[]; type: string }>, mesh: Mesh | LinesMesh, bounds: TerrainBounds): boolean {
  const id = segmentIdFromMeshName(mesh.name);
  if (id !== null) {
    const segment = segmentsById.get(id);
    if (!segment) return true;
    return segmentMeshTouchesBounds(segment.samples, roadType(segment.type), bounds);
  }
  mesh.computeWorldMatrix(true);
  const box = mesh.getBoundingInfo().boundingBox;
  return box.maximumWorld.x >= bounds.minX && box.minimumWorld.x <= bounds.maxX && box.maximumWorld.z >= bounds.minZ && box.minimumWorld.z <= bounds.maxZ;
}

function pointTouchesBounds(p: Vec3, bounds: TerrainBounds): boolean {
  return p.x >= bounds.minX && p.x <= bounds.maxX && p.z >= bounds.minZ && p.z <= bounds.maxZ;
}

function segmentTouchesBounds(a: Vec3, b: Vec3, bounds: TerrainBounds): boolean {
  if (Math.max(a.x, b.x) < bounds.minX || Math.min(a.x, b.x) > bounds.maxX || Math.max(a.z, b.z) < bounds.minZ || Math.min(a.z, b.z) > bounds.maxZ) return false;
  return (
    linesIntersect(a, b, { x: bounds.minX, y: 0, z: bounds.minZ }, { x: bounds.maxX, y: 0, z: bounds.minZ }) ||
    linesIntersect(a, b, { x: bounds.maxX, y: 0, z: bounds.minZ }, { x: bounds.maxX, y: 0, z: bounds.maxZ }) ||
    linesIntersect(a, b, { x: bounds.maxX, y: 0, z: bounds.maxZ }, { x: bounds.minX, y: 0, z: bounds.maxZ }) ||
    linesIntersect(a, b, { x: bounds.minX, y: 0, z: bounds.maxZ }, { x: bounds.minX, y: 0, z: bounds.minZ })
  );
}

function linesIntersect(a: Vec3, b: Vec3, c: Vec3, d: Vec3): boolean {
  const side = (p: Vec3, q: Vec3, r: Vec3) => Math.sign((q.x - p.x) * (r.z - p.z) - (q.z - p.z) * (r.x - p.x));
  const abC = side(a, b, c);
  const abD = side(a, b, d);
  const cdA = side(c, d, a);
  const cdB = side(c, d, b);
  return abC !== abD && cdA !== cdB;
}

function segmentIdFromMeshName(name: string): number | null {
  const match = /^(?:road|curb|guardrail_[lr]|sidewalk|lane|traffic_lane|traffic_walk|traffic_lane_change|tunnel_trace|tunnel|bridge_(?:pier|pylon|cable)|roundabout_gap|roundabout_splitter|roundabout_corner)_(\d+)/.exec(name);
  return match ? Number(match[1]) : null;
}

/** `offset` moves the sampled line sideways from the centreline, for a lane drawn off-centre. */
function pointsBetween(
  graph: RoadGraph,
  id: number,
  from: number,
  to: number,
  steps: number,
  lift: number,
  heightAt: (x: number, z: number) => number,
  offset = 0,
): Vector3[] {
  const points: Vector3[] = [];
  for (let i = 0; i <= steps; i++) {
    const d = from + ((to - from) * i) / steps;
    const { position, tangent } = graph.pointAt(id, d);
    const y = Math.max(position.y, heightAt(position.x, position.z)) + lift;
    if (offset === 0) {
      points.push(new Vector3(position.x, y, position.z));
    } else {
      const n = perpXZ(normalizeXZ(tangent));
      points.push(new Vector3(position.x + n.x * offset, y, position.z + n.z * offset));
    }
  }
  return points;
}

function tunnelMesh(scene: Scene, name: string, graph: RoadGraph, id: number, steps: number, width: number): { shell: Mesh; interior: Mesh } {
  const seg = graph.segment(id);
  const inner = tunnelSection(width);
  const outer = tunnelSection(width + 8).map((p) => ({ x: p.x, y: p.y + 1.5 }));
  const shellPositions: number[] = [];
  const interiorPositions: number[] = [];
  for (let i = 0; i <= steps; i++) {
    const { position, tangent } = graph.pointAt(id, (seg.length * i) / steps);
    const n = perpXZ(normalizeXZ(tangent));
    const y = position.y + ROAD_LIFT;
    for (const p of outer) shellPositions.push(position.x + n.x * p.x, y + p.y, position.z + n.z * p.x);
    for (const p of inner) interiorPositions.push(position.x + n.x * p.x, y + p.y, position.z + n.z * p.x);
  }
  const shellIndices = tunnelStripIndices(outer.length, steps, false);
  const interiorIndices = tunnelStripIndices(inner.length, steps, true);
  return {
    shell: vertexMesh(scene, `${name}_shell`, shellPositions, shellIndices),
    interior: vertexMesh(scene, `${name}_interior`, interiorPositions, interiorIndices),
  };
}

export function tunnelStripIndices(count: number, steps: number, flip: boolean): number[] {
  const indices: number[] = [];
  for (let i = 0; i < steps; i++) {
    const a = i * count;
    const b = a + count;
    for (let j = 0; j < count - 1; j++) {
      if (flip) indices.push(a + j, a + j + 1, b + j, a + j + 1, b + j + 1, b + j);
      else indices.push(a + j, b + j, a + j + 1, a + j + 1, b + j, b + j + 1);
    }
  }
  return indices;
}

function vertexMesh(scene: Scene, name: string, positions: number[], indices: number[]): Mesh {
  const mesh = new MeshClass(name, scene);
  const data = new VertexData();
  data.positions = positions;
  data.indices = indices;
  const normals: number[] = [];
  VertexData.ComputeNormals(positions, indices, normals);
  data.normals = normals;
  data.applyToMesh(mesh);
  return mesh;
}

export function tunnelSection(width: number): { x: number; y: number }[] {
  const gateWidth = width + 8;
  const wall = 3;
  const arch = 5;
  const half = gateWidth / 2;
  return [
    { x: -half, y: 0 },
    { x: -half, y: wall },
    ...Array.from({ length: 7 }, (_, i) => {
      const x = -half + (gateWidth * i) / 6;
      return { x, y: wall + arch * Math.sqrt(1 - (x / half) ** 2) };
    }),
    { x: half, y: wall },
    { x: half, y: 0 },
  ];
}

function tunnelPortals(
  scene: Scene,
  graph: RoadGraph,
  id: number,
  width: number,
  material: StandardMaterial,
  color: Color3,
  heightAt: (x: number, z: number) => number,
): (Mesh | LinesMesh)[] {
  const seg = graph.segment(id);
  return [
    ...tunnelPortal(scene, graph, id, 0, width, 1, material, color, heightAt),
    ...tunnelPortal(scene, graph, id, seg.length, width, -1, material, color, heightAt),
  ];
}

function tunnelPortal(
  scene: Scene,
  graph: RoadGraph,
  id: number,
  distance: number,
  width: number,
  direction: 1 | -1,
  material: StandardMaterial,
  color: Color3,
  heightAt: (x: number, z: number) => number,
): (Mesh | LinesMesh)[] {
  const { position, tangent } = graph.pointAt(id, distance);
  const y = heightAt(position.x, position.z) + MARK_LIFT;
  const exterior = portalExterior(scene, `tunnel_headwall_${id}_${distance}`, position, tangent, width, direction, y);
  for (const mesh of exterior) {
    mesh.material = material;
    mesh.isPickable = false;
  }

  const portal = portalMesh(scene, `tunnel_portal_${id}_${distance}`, position, tangent, width, direction, y);
  portal.material = material;
  portal.isPickable = false;

  const lip = portalOutline(position, tangent, width, y);
  return [...exterior, portal, styledLine(scene, `tunnel_lip_${id}_${distance}`, lip, color)];
}

function portalExterior(
  scene: Scene,
  name: string,
  center: { x: number; z: number },
  tangent: { x: number; z: number },
  width: number,
  direction: 1 | -1,
  y: number,
): Mesh[] {
  const gate = width + 8;
  const side = 5;
  const height = 9;
  const top = 3;
  const depth = 5;
  const rotation = Math.atan2(tangent.x * direction, tangent.z * direction);
  const n = perpXZ(normalizeXZ({ x: tangent.x, y: 0, z: tangent.z }));
  const block = (label: string, x: number, boxWidth: number, boxHeight: number, cy: number) => {
    const mesh = MeshBuilder.CreateBox(`${name}_${label}`, { width: boxWidth, height: boxHeight, depth }, scene);
    mesh.position.set(center.x + n.x * x, cy, center.z + n.z * x);
    mesh.rotation.y = rotation;
    return mesh;
  };
  return [
    block("left", -gate / 2 - side / 2, side, height, y + height / 2),
    block("right", gate / 2 + side / 2, side, height, y + height / 2),
    block("top", 0, gate + side * 2, top, y + height + top / 2),
  ];
}

function portalMesh(
  scene: Scene,
  name: string,
  center: { x: number; z: number },
  tangent: { x: number; z: number },
  width: number,
  direction: 1 | -1,
  y: number,
): Mesh {
  const t = normalizeXZ({ x: tangent.x * direction, y: 0, z: tangent.z * direction });
  const n = perpXZ(t);
  const inner = tunnelSection(width);
  const outer = tunnelSection(width + 8).map((p) => ({ x: p.x, y: p.y + 1.5 }));
  const positions: number[] = [];
  for (const d of [-1.4, 1.4]) {
    for (const section of [outer, inner]) {
      for (const p of section) positions.push(center.x + n.x * p.x + t.x * d, y + p.y, center.z + n.z * p.x + t.z * d);
    }
  }
  const indices: number[] = [];
  const count = inner.length;
  const frontOuter = 0;
  const frontInner = count;
  const backOuter = count * 2;
  const backInner = count * 3;
  for (let i = 0; i < count - 1; i++) {
    indices.push(frontOuter + i, frontOuter + i + 1, frontInner + i, frontOuter + i + 1, frontInner + i + 1, frontInner + i);
    indices.push(backOuter + i, backInner + i, backOuter + i + 1, backOuter + i + 1, backInner + i, backInner + i + 1);
    indices.push(frontOuter + i, backOuter + i, frontOuter + i + 1, frontOuter + i + 1, backOuter + i, backOuter + i + 1);
    indices.push(frontInner + i, frontInner + i + 1, backInner + i, frontInner + i + 1, backInner + i + 1, backInner + i);
  }
  const mesh = new MeshClass(name, scene);
  const data = new VertexData();
  data.positions = positions;
  data.indices = indices;
  const normals: number[] = [];
  VertexData.ComputeNormals(positions, indices, normals);
  data.normals = normals;
  data.applyToMesh(mesh);
  return mesh;
}

export function portalOutline(center: { x: number; z: number }, tangent: { x: number; z: number }, width: number, y: number): Vector3[] {
  const n = perpXZ(normalizeXZ({ x: tangent.x, y: 0, z: tangent.z }));
  return tunnelSection(width).map((p) => new Vector3(center.x + n.x * p.x, y + p.y, center.z + n.z * p.x));
}

/** Surface only: terrain clearance is handled by earthworks, without extruded pavement sides. */
function roadStripMesh(scene: Scene, name: string, left: Vector3[], right: Vector3[], ...more: [Vector3[], Vector3[]][]): Mesh {
  const positions: number[] = [];
  const indices: number[] = [];
  for (const [l, r] of [[left, right] as [Vector3[], Vector3[]], ...more]) {
    const base = positions.length / 3;
    for (let i = 0; i < l.length; i++) {
      positions.push(l[i]!.x, l[i]!.y, l[i]!.z, r[i]!.x, r[i]!.y, r[i]!.z);
    }
    for (let i = 0; i < l.length - 1; i++) {
      const a = base + i * 2;
      const b = a + 2;
      indices.push(a, a + 1, b, a + 1, b + 1, b);
    }
  }
  const mesh = new MeshClass(name, scene);
  const data = new VertexData();
  data.positions = positions;
  data.indices = indices;
  data.normals = Array.from({ length: positions.length / 3 }, () => [0, 1, 0]).flat();
  data.applyToMesh(mesh);
  return mesh;
}

/**
 * A triangle fan from the ring's centroid. The ring is convex, so a fan tessellates it
 * exactly -- no earcut, no dependency.
 */
function junctionMesh(scene: Scene, junction: JunctionGeometry): Mesh | null {
  const ring = junction.ring;
  if (ring.length < 3) return null;

  let cx = 0;
  let cy = 0;
  let cz = 0;
  for (const p of ring) {
    cx += p.x;
    cy += p.y;
    cz += p.z;
  }
  cx /= ring.length;
  cy /= ring.length;
  cz /= ring.length;

  const positions: number[] = [cx, cy + ROAD_LIFT, cz];
  for (const p of ring) positions.push(p.x, p.y + ROAD_LIFT, p.z);

  const indices: number[] = [];
  for (let i = 0; i < ring.length; i++) {
    indices.push(0, 1 + i, 1 + ((i + 1) % ring.length));
  }

  const mesh = new MeshClass(`junction_${junction.node}`, scene);
  const data = new VertexData();
  data.positions = positions;
  // Wound both ways, because the hull's winding can come out either way and a junction
  // culled from above is a hole. The normals are set explicitly rather than derived: a
  // horizontal polygon's normal is known, and deriving it from two windings cancels out.
  data.indices = [...indices, ...indices.slice().reverse()];
  data.normals = Array.from({ length: positions.length / 3 }, () => [0, 1, 0]).flat();
  data.applyToMesh(mesh);
  return mesh;
}
